spring.application.name=healthtrack-backend
server.port=8081

spring.datasource.url=jdbc:postgresql://dpg-db1qa1s9v7es738o9qng-a:5432/healthtrack_db_7ghr
spring.datasource.username=healthtrack_db_7ghr_user
spring.datasource.password=6moYQrfhriBPXG6gZ4rCLuslUy42yU6I

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
